name: Feature
description: New feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: goal
    attributes: { label: Problem / Goal }
  - type: textarea
    id: acceptance
    attributes: { label: Acceptance Criteria, description: "Bulleted list" }
  - type: dropdown
    id: size
    attributes: { label: Size, options: ["S","M","L"] }
