name: Task
description: Small task/checklist
title: "[Task]: "
labels: ["docs"]
body:
  - type: checkboxes
    id: steps
    attributes:
      label: Steps
      options:
        - label: "Do the thing"
        - label: "Verify it works"
